services:
  - type: web
    name: fin-sight
    env: python
    plan: free
    buildCommand: "bash build.sh"
    startCommand: "gunicorn finsight.wsgi:application"
    envVars:
      - key: DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: "3.11.10"
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_SUPERUSER_USERNAME
        value: "admin"
      - key: DJANGO_SUPERUSER_PASSWORD
        value: "AdminPassword123!"
      - key: DJANGO_SUPERUSER_EMAIL
        value: "admin@finsight.com"

# PostgreSQL service removed temporarily
# Will add back when switching to PostgreSQL later
