# Generated by Django 5.2.7 on 2025-11-07 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_ledgerupload_high_risk_count_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("transaction_summary", "Transaction Summary"),
                            ("risk_analysis", "Risk Analysis Report"),
                            ("alert_summary", "Alert Summary"),
                            ("compliance_report", "Compliance Report"),
                            ("user_activity", "User Activity Report"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "date_range_days",
                    models.PositiveIntegerField(
                        default=30, help_text="Number of days to include in report"
                    ),
                ),
                ("include_charts", models.BooleanField(default=True)),
                ("include_raw_data", models.BooleanField(default=False)),
                (
                    "recipients",
                    models.JSONField(
                        default=list,
                        help_text="List of email addresses to send report to",
                    ),
                ),
                ("risk_threshold_min", models.FloatField(blank=True, null=True)),
                ("risk_threshold_max", models.FloatField(blank=True, null=True)),
                ("include_high_risk_only", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("last_run", models.DateTimeField(blank=True, null=True)),
                ("next_run", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReportInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("generating", "Generating"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                (
                    "pdf_file",
                    models.FileField(blank=True, null=True, upload_to="reports/pdf/"),
                ),
                (
                    "excel_file",
                    models.FileField(blank=True, null=True, upload_to="reports/excel/"),
                ),
                (
                    "csv_file",
                    models.FileField(blank=True, null=True, upload_to="reports/csv/"),
                ),
                ("summary_data", models.JSONField(default=dict)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instances",
                        to="core.report",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
